UPDATE GlobalParameters SET Value = 20 WHERE Name='START_DISTANCE_MAJOR_CIVILIZATION';
UPDATE GlobalParameters SET Value = 8 WHERE Name='START_DISTANCE_MINOR_CIVILIZATION_START';
UPDATE GlobalParameters SET Value = 6 WHERE Name='START_DISTANCE_MINOR_MAJOR_CIVILIZATION';

UPDATE GlobalParameters SET Value = 0 WHERE Name='START_DISTANCE_MAJOR_NATURAL_WONDER';
UPDATE GlobalParameters SET Value = 0 WHERE Name='START_DISTANCE_MINOR_NATURAL_WONDER';